### ISSUE TITLE
CR comment count rethinking?

### ISSUE THREAD

**Issue by amihaiemil** [teamed/xdsd#51]
It is a good practice to give the CR a bonus for comments - it encourages them to point out the bad things. 

However, there should be a limit or a different way of counting (not brutely count all of them). 
Because right now, it is **convenient** for the CR to delay their work, leave as many comments as possible and point out all the most cosmetic things just because.

It happens too often to me that my tasks are **delayed** and most of the time they are in CR. 
I have the feeling the CR simply thinks "why not leave this thing for tomorrow and have another exchange of comments on it?", instead of pointing it out in the same comment with the others, today.

**Comment by mkordas** [comment]
@amihaiemil 
> why not leave this thing for tomorrow and have another exchange of comments on it

That would be pretty unprofessional. It's not always possible to do a full code review just after PR is submitted because it takes significant amount of time and focus. I believe it's better to provide early feedback about some part of PR than waiting a few days for a full review. Moreover, the more times you visit PR, the more you understand it and the more tiny details you notice. It takes some time, but at the end I believe it has good impact on keeping technical debt as small as possible.

**Comment by amihaiemil** [comment]
@mkordas i understand what ure saying and it makes sense. But it's the tiny unsignifiant details that the time is wasted on. And ok, let it be, but then I am "punished", I lose time and rating because the CR did not like some cosmetic details and keeps bugging me with them. I work with teamed sine January and I simply cannot get a rating past 500, it's all a game of "1 step forward-2 steps back".

Then of course, at the end of the dat it's consodered to be my fault...

**Comment by amihaiemil** [comment]
@mkordas then there is automated PM. What's the scope of working with chatbots if they take action worse than a human?? 

I dont mean payments, I understand that. I mean closing and assignment of new tasks: that should be done in the second the pr is merged, I tell it to close, it checks for the deleted todo, closes and assigns me a new task. Then pays me the next day or so.
